"use client";
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {supabaseBrowser} from '../../../lib/supabase';

declare global{interface Window{XLSX?:any}}

type Row={name:string;category:string;set:string;card_number:string;rarity:string;language:string;condition:string;price:number;stock:number;published:boolean;status:string;error?:string};
const keys=['Nombre','Categoría','Set','Referencia','Rareza','Idioma','Condición','Precio','Stock','Publicada'];
const norm=(v:any)=>String(v??'').trim();
const pick=(r:any,names:string[])=>{const k=Object.keys(r).find(x=>names.includes(x.trim().toLowerCase()));return k?r[k]:''};
export default function Importaciones(){const router=useRouter(),sb=supabaseBrowser();const[ok,setOk]=useState(false),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[rows,setRows]=useState<Row[]>([]),[fileName,setFileName]=useState('');
useEffect(()=>{(async()=>{const{data:u}=await sb.auth.getUser();if(!u.user){router.replace('/login');return}const{data:p}=await sb.from('profiles').select('role').eq('id',u.user.id).maybeSingle();if(p?.role!=='admin'){router.replace('/login');return}setOk(true);if(!window.XLSX){const s=document.createElement('script');s.src='https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js';document.head.appendChild(s)}})()},[]);
function parseFile(file:File){setBusy(true);setMsg('');setFileName(file.name);const reader=new FileReader();reader.onload=e=>{try{if(!window.XLSX)throw new Error('El lector Excel aún está cargando. Intenta de nuevo.');const wb=window.XLSX.read(e.target?.result,{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]],data=window.XLSX.utils.sheet_to_json(ws,{defval:''});const seen=new Set<string>();const parsed:Row[]=data.map((r:any,i:number)=>{const name=norm(pick(r,['nombre','name'])),category=norm(pick(r,['categoría','categoria','category'])),set=norm(pick(r,['set','expansión','expansion'])),card_number=norm(pick(r,['referencia','sku','card_number','numero','número'])),rarity=norm(pick(r,['rareza','rarity'])),language=norm(pick(r,['idioma','language']))||'English',condition=norm(pick(r,['condición','condicion','condition']))||'Near Mint',price=Number(pick(r,['precio','price'])),stock=Number(pick(r,['stock','existencia','existencias'])),published=!['no','false','0','oculto'].includes(norm(pick(r,['publicada','published'])).toLowerCase()),key=`${name.toLowerCase()}|${card_number.toLowerCase()}|${set.toLowerCase()}`;let error='';if(!name)error='Falta Nombre';else if(!category)error='Falta Categoría';else if(!Number.isFinite(price)||price<0)error='Precio inválido';else if(!Number.isInteger(stock)||stock<0)error='Stock inválido';else if(seen.has(key))error='Duplicado dentro del archivo';seen.add(key);return{name,category,set,card_number,rarity,language,condition,price,stock,published,status:error?'ERROR':'LISTO',error}});setRows(parsed);setMsg(`${parsed.length} filas cargadas. ${parsed.filter(r=>r.status==='ERROR').length} con errores.`)}catch(err:any){setMsg(err.message||'No se pudo leer el archivo.');setRows([])}setBusy(false)};reader.readAsArrayBuffer(file)}
async function confirmImport(){if(!rows.length)return;const bad=rows.filter(r=>r.status==='ERROR');if(bad.length){setMsg('Corrige las filas con error antes de confirmar.');return}setBusy(true);setMsg('Validando categorías y sets...');const[{data:cats,error:ce},{data:sets,error:se},{data:cards,error:cardErr}]=await Promise.all([sb.from('categories').select('*'),sb.from('sets').select('*'),sb.from('cards').select('*')]);if(ce||se||cardErr){setMsg((ce||se||cardErr)?.message||'Error consultando inventario.');setBusy(false);return}const catMap=new Map((cats||[]).map((x:any)=>[x.name.trim().toLowerCase(),x.id])),setMap=new Map((sets||[]).map((x:any)=>[x.name.trim().toLowerCase(),x.id]));const errors:Row[]=[],ready:Row[]=[];for(const r of rows){if(!catMap.has(r.category.trim().toLowerCase())){errors.push({...r,status:'ERROR',error:`Categoría no encontrada: ${r.category}`});continue}if(r.set&&!setMap.has(r.set.trim().toLowerCase())){errors.push({...r,status:'ERROR',error:`Set no encontrado: ${r.set}`});continue}ready.push(r)}if(errors.length){setRows([...ready,...errors]);setMsg(`${errors.length} filas requieren corrección: categorías o sets inexistentes.`);setBusy(false);return}let created=0,updated=0;for(const r of ready){const category_id=catMap.get(r.category.trim().toLowerCase()),set_id=r.set?setMap.get(r.set.trim().toLowerCase()):null;const existing=(cards||[]).find((c:any)=>String(c.name).trim().toLowerCase()===r.name.trim().toLowerCase()&&String(c.card_number||'').trim().toLowerCase()===r.card_number.trim().toLowerCase()&&((c.set_id||null)===(set_id||null)));const payload={name:r.name,category_id,set_id,card_number:r.card_number||null,rarity:r.rarity||null,language:r.language,condition:r.condition,price:r.price,stock:r.stock,published:r.published};const res=existing?await sb.from('cards').update(payload).eq('id',existing.id):await sb.from('cards').insert(payload);if(res.error){setMsg(`Error en ${r.name}: ${res.error.message}`);setBusy(false);return}existing?updated++:created++}setMsg(`Importación completada: ${created} nuevos, ${updated} actualizados.`);setRows([]);setBusy(false)}
async function exportInventory(){if(!window.XLSX)return;setBusy(true);const{data,error}=await sb.from('cards').select('*,categories(name),sets(name)').order('created_at',{ascending:false});if(error){setMsg(error.message);setBusy(false);return}const out=(data||[]).map((c:any)=>({'Nombre':c.name,'Categoría':c.categories?.name||'','Set':c.sets?.name||'','Referencia':c.card_number||'','Rareza':c.rarity||'','Idioma':c.language,'Condición':c.condition,'Precio':c.price,'Stock':c.stock,'Publicada':c.published?'Sí':'No'}));const wb=window.XLSX.utils.book_new(),ws=window.XLSX.utils.json_to_sheet(out);window.XLSX.utils.book_append_sheet(wb,ws,'Inventario');window.XLSX.writeFile(wb,`la-comarca-inventario-${new Date().toISOString().slice(0,10)}.xlsx`);setMsg(`${out.length} productos exportados.`);setBusy(false)}
if(!ok)return <main className="wrap"><div className="empty">Verificando acceso...</div></main>;const errors=rows.filter(r=>r.status==='ERROR').length;return <><header className="top"><a href="/admin">← Administración</a><b>La Comarca · Inventario / Excel</b></header><main className="wrap"><div className="panel"><h1>Inventario · Excel</h1><p className="muted">Importa sin modificar el inventario hasta confirmar. Las filas se validan antes de guardar.</p><div className="actions"><label className="btn" style={{display:'inline-block',cursor:'pointer'}}>📥 Seleccionar Excel<input type="file" accept=".xlsx,.xls,.csv" style={{display:'none'}} onChange={e=>{const f=e.target.files?.[0];if(f)parseFile(f)}}/></label><button className="btn2" disabled={busy} onClick={exportInventory}>📤 Exportar inventario</button></div>{fileName&&<p><b>{fileName}</b></p>}{msg&&<p className="notice">{msg}</p>}</div>{rows.length>0&&<div className="panel"><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'}}><div><h2 style={{marginBottom:4}}>Vista previa ({rows.length})</h2><span className="muted">{errors?`${errors} con error`:'Todas listas para importar'}</span></div><button className="btn" disabled={busy||errors>0} onClick={confirmImport}>✓ Confirmar importación</button></div><div style={{overflow:'auto',marginTop:16}}><table className="table"><thead><tr>{keys.map(k=><th key={k}>{k}</th>)}<th>Validación</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td>{r.name}</td><td>{r.category}</td><td>{r.set}</td><td>{r.card_number}</td><td>{r.rarity}</td><td>{r.language}</td><td>{r.condition}</td><td>${r.price.toLocaleString('es-MX')}</td><td>{r.stock}</td><td>{r.published?'Sí':'No'}</td><td>{r.status==='ERROR'?<span style={{color:'#a23b35'}}>{r.error}</span>:<span style={{color:'#35654d'}}>LISTO</span>}</td></tr>)}</tbody></table></div></div>}</main></>}
