"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import * as XLSX from "xlsx";
import JSZip from "jszip";
import {supabaseBrowser} from "../../../lib/supabase";

type Row=Record<string,any>;
const REQUIRED=["Nombre","Categoría","Precio MXN","Stock"];
const HEADERS=["ID FOTO","Nombre","Categoría","Set","Número","Rareza","Idioma","Condición","Precio MXN","Stock","Publicado","Ubicación","Notas","Imagen"];
const photoId=(n:number)=>`LC-${String(n).padStart(6,"0")}`;
const clean=(v:any)=>String(v||"").trim().replace(/^.*[\\/]/,"").toLowerCase();
const isPhoto=(name:string,id:string)=>{const n=clean(name);return [".jpg",".jpeg",".png",".webp"].some(ext=>n===`${id}${ext}`)};

export default function Inventario(){
 const router=useRouter(),sb=supabaseBrowser();
 const [busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[role,setRole]=useState(""),[preview,setPreview]=useState<Row[]>([]),[errors,setErrors]=useState<string[]>([]),[rows,setRows]=useState<Row[]>([]),[total,setTotal]=useState(0),[photos,setPhotos]=useState(0),[zipFile,setZipFile]=useState<File|null>(null);
 useEffect(()=>{(async()=>{const {data:u}=await sb.auth.getUser();if(!u.user){router.replace('/login');return}const {data:p}=await sb.from('profiles').select('role').eq('id',u.user.id).maybeSingle();if(!p||!['admin','agent'].includes(p.role)){await sb.auth.signOut();router.replace('/login');return}setRole(p.role)})()},[]);
 function makeXlsx(data:Row[],name:string){const ws=XLSX.utils.json_to_sheet(data,{header:HEADERS});const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Inventario");XLSX.writeFile(wb,name)}
 async function exportXlsx(){setBusy(true);const {data,error}=await sb.from('cards').select('id,name,category_id,set_id,card_number,rarity,language,condition,price,stock,published,image_url,categories(name),sets(name)');if(error){setMsg(error.message);setBusy(false);return}const dataRows=(data||[]).map((c:any,i:number)=>({"ID FOTO":photoId(i+1),Nombre:c.name,Categoría:c.categories?.name||"",Set:c.sets?.name||"",Número:c.card_number||"",Rareza:c.rarity||"",Idioma:c.language||"English",Condición:c.condition||"Near Mint","Precio MXN":Number(c.price),Stock:c.stock,Publicado:c.published?'Sí':'No',Ubicación:"",Notas:"",Imagen:c.image_url||""}));makeXlsx(dataRows,`la-comarca-inventario-${new Date().toISOString().slice(0,10)}.xlsx`);setMsg(`Exportación lista: ${dataRows.length} producto(s).`);setBusy(false)}
 function downloadTemplate(){const data=Array.from({length:100},(_,i)=>({"ID FOTO":photoId(i+1),Nombre:"",Categoría:"",Set:"",Número:"",Rareza:"",Idioma:"English",Condición:"Near Mint","Precio MXN":"",Stock:"",Publicado:"Sí",Ubicación:"",Notas:"",Imagen:`fotos/${photoId(i+1)}.jpg`}));makeXlsx(data,"la-comarca-plantilla-inventario.xlsx");setMsg("Plantilla creada con 100 IDs de foto.")}
 function validate(data:Row[]){const out:string[]=[];data.forEach((r,i)=>{REQUIRED.forEach(k=>{if(r[k]===undefined||r[k]==="")out.push(`Fila ${i+2}: falta ${k}.`)});if(r["Precio MXN"]!==""&&!Number.isFinite(Number(r["Precio MXN"])))out.push(`Fila ${i+2}: Precio MXN inválido.`);if(r.Stock!==""&&(!Number.isInteger(Number(r.Stock))||Number(r.Stock)<0))out.push(`Fila ${i+2}: Stock inválido.`);if(r["ID FOTO"]&&!/^LC-\d{6}$/.test(String(r["ID FOTO"])))out.push(`Fila ${i+2}: ID FOTO inválido.`)});return out.slice(0,100)}
 async function prepare(data:Row[],photoNames:string[]=[]){const errs=validate(data);const missing:string[]=[];if(photoNames.length){data.forEach((r,i)=>{const id=clean(r["ID FOTO"]);if(id&&!photoNames.some(n=>isPhoto(n,id)))missing.push(`Fila ${i+2}: no se encontró foto para ${r["ID FOTO"]}.`)})}setRows(data);setTotal(data.length);setPreview(data.slice(0,10));setPhotos(photoNames.length);setErrors([...errs,...missing].slice(0,100));setMsg(errs.length||missing.length?`Se detectaron ${errs.length+missing.length} problema(s).`:`${data.length} fila(s) listas para revisión.`)}
 async function readXlsx(file:File){try{const wb=XLSX.read(await file.arrayBuffer(),{type:'array'});const sheet=wb.Sheets.Inventario||wb.Sheets[wb.SheetNames[0]];await prepare(XLSX.utils.sheet_to_json<Row>(sheet,{defval:""}))}catch(e:any){setErrors([`No se pudo leer el Excel: ${e.message}`])}}
 async function readZip(file:File){setZipFile(file);try{const zip=await JSZip.loadAsync(file);const entry=Object.values(zip.files).find((f:any)=>!f.dir&&f.name.toLowerCase().endsWith('.xlsx'));if(!entry)throw new Error('El ZIP debe contener un archivo .xlsx.');const wb=XLSX.read(await entry.async('arraybuffer'),{type:'array'});const sheet=wb.Sheets.Inventario||wb.Sheets[wb.SheetNames[0]];const data=XLSX.utils.sheet_to_json<Row>(sheet,{defval:""});const names=Object.values(zip.files).filter((f:any)=>!f.dir).map((f:any)=>f.name).filter((n:string)=>/\.(jpg|jpeg|png|webp)$/i.test(n));await prepare(data,names)}catch(e:any){setErrors([`No se pudo leer el ZIP: ${e.message}`]);setPreview([])}}
 async function importInventory(){if(!rows.length||errors.length)return;setBusy(true);setMsg("Importando...");const {data:u}=await sb.auth.getUser();if(!u.user){router.replace('/login');return}let zip:JSZip|null=null;if(zipFile)zip=await JSZip.loadAsync(zipFile);const {data:cats}=await sb.from('categories').select('id,name');const {data:sets}=await sb.from('sets').select('id,name,code');const catMap=new Map((cats||[]).map((x:any)=>[String(x.name).trim().toLowerCase(),x.id]));const setMap=new Map<string,any>();(sets||[]).forEach((x:any)=>{setMap.set(String(x.name).trim().toLowerCase(),x.id);if(x.code)setMap.set(String(x.code).trim().toLowerCase(),x.id)});let created=0,rejected=0,uploaded=0;const details:any[]=[];for(let i=0;i<rows.length;i++){const r=rows[i];try{const categoryId=catMap.get(String(r["Categoría"]).trim().toLowerCase());if(!categoryId)throw new Error(`Categoría no encontrada: ${r["Categoría"]}`);const setId=r.Set?setMap.get(String(r.Set).trim().toLowerCase())||null:null;let image_url:string|null=null;const id=clean(r["ID FOTO"]);if(zip&&id){const file=Object.values(zip.files).find((f:any)=>!f.dir&&isPhoto(f.name,id)) as any;if(file){const blob=await file.async('blob');const ext=String(file.name).split('.').pop()?.toLowerCase()||'jpg';const path=`inventory/${u.user.id}/${id}.${ext}`;const up=await sb.storage.from('card-images').upload(path,blob,{upsert:true,contentType:blob.type||'image/jpeg'});if(up.error)throw up.error;image_url=sb.storage.from('card-images').getPublicUrl(path).data.publicUrl;uploaded++}}else if(String(r.Imagen||'').startsWith('http://')||String(r.Imagen||'').startsWith('https://'))image_url=String(r.Imagen).trim();const payload={name:String(r.Nombre).trim(),category_id:categoryId,set_id:setId,card_number:r.Número?String(r.Número):null,rarity:r.Rareza?String(r.Rareza):null,language:String(r.Idioma||'English'),condition:String(r.Condición||'Near Mint'),price:Number(r["Precio MXN"]),stock:Number(r.Stock),published:String(r.Publicado||'Sí').toLowerCase()==='sí',image_url,created_by:u.user.id,updated_by:u.user.id};const res=await sb.from('cards').insert(payload);if(res.error)throw res.error;created++}catch(e:any){rejected++;details.push({row:i+2,error:e.message||String(e)})}}setBusy(false);setErrors(details.map(d=>`Fila ${d.row}: ${d.error}`).slice(0,100));setPreview([]);setMsg(`Importación terminada: ${created} creados, ${rejected} rechazados, ${uploaded} fotos asociadas.`)}
 return <><header className="top"><a href="/admin">← Administración</a><b>La Comarca · Inventario</b><div className="actions"><button className="btn2" onClick={exportXlsx}>⬇ Exportar XLSX</button><button className="btn2" onClick={()=>router.push('/catalogo')}>Catálogo</button></div></header><main className="wrap"><div className="panel"><h2>Importar inventario</h2><p className="muted">Acceso: {role}. Excel solo o ZIP con Excel + fotos.</p><div className="actions"><button className="btn2" onClick={downloadTemplate}>📄 Descargar plantilla Excel</button><label className="btn2" style={{cursor:'pointer'}}>📥 Seleccionar Excel<input hidden type="file" accept=".xlsx" onChange={e=>{const f=e.target.files?.[0];if(f){setZipFile(null);readXlsx(f)}}}/></label><label className="btn2" style={{cursor:'pointer'}}>📦 Seleccionar ZIP con fotos<input hidden type="file" accept=".zip" onChange={e=>{const f=e.target.files?.[0];if(f)readZip(f)}}/></label></div><p className="muted">ZIP: <b>inventario.xlsx</b> + <b>fotos/</b>. Nombra cada foto con su ID: <b>LC-000001.jpg</b>.</p>{total>0&&<p>{total} fila(s) · {photos} foto(s) detectadas.</p>}{errors.length>0&&<div className="notice">{errors.map((e,i)=><div key={i}>{e}</div>)}</div>}{total>0&&!errors.length&&<div className="notice">✓ Archivo válido. Vista previa de hasta 10 filas.</div>}{total>0&&!errors.length&&<button className="btn" disabled={busy} onClick={importInventory}>{busy?'Importando...':'Confirmar importación'}</button>}{msg&&<p className="notice">{msg}</p>}</div>{preview.length>0&&<div className="panel"><h3>Vista previa</h3><div style={{overflow:'auto'}}><table className="table"><thead><tr>{Object.keys(preview[0]).map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{preview.map((r,i)=><tr key={i}>{Object.keys(preview[0]).map(k=><td key={k}>{String(r[k]??'')}</td>)}</tr>)}</tbody></table></div></div>}<div className="panel"><h3>Cómo preparar las fotos</h3><ol><li>Descarga la plantilla; ya incluye IDs como <b>LC-000001</b>.</li><li>Toma cada foto y nómbrala con su ID.</li><li>Guarda las fotos en <b>fotos/</b>.</li><li>Comprime Excel + fotos en un ZIP.</li></ol></div></main></>;
}