"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import * as XLSX from "xlsx";
import JSZip from "jszip";
import {supabaseBrowser} from "../../../lib/supabase";

type Row=Record<string,any>;
const REQUIRED=["Nombre","Categoría","Precio MXN","Stock"];
const HEADERS=["ID FOTO","Nombre","Categoría","Set","Número","Rareza","Idioma","Condición","Precio MXN","Stock","Publicado","Ubicación","Notas","Imagen"];

function photoId(n:number){return `LC-${String(n).padStart(6,"0")}`}
function cleanPhotoName(v:any){return String(v||"").trim().replace(/^.*[\\/]/,"").toLowerCase()}

export default function Inventario(){
 const router=useRouter(); const sb=supabaseBrowser();
 const [busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[role,setRole]=useState(""),[preview,setPreview]=useState<Row[]>([]),[errors,setErrors]=useState<string[]>([]),[totalRows,setTotalRows]=useState(0),[photoCount,setPhotoCount]=useState(0),[zipFile,setZipFile]=useState<File|null>(null),[rowsForImport,setRowsForImport]=useState<Row[]>([]);
 useEffect(()=>{(async()=>{const {data:u}=await sb.auth.getUser();if(!u.user){router.replace('/login');return}const {data:p}=await sb.from('profiles').select('role').eq('id',u.user.id).maybeSingle();if(!p||!['admin','agent'].includes(p.role)){await sb.auth.signOut();router.replace('/login');return}setRole(p.role)})()},[]);
 async function exportXlsx(){setBusy(true);setMsg("");const {data,error}=await sb.from('cards').select('id,name,category_id,set_id,card_number,rarity,language,condition,price,stock,published,image_url,categories(name),sets(name)');if(error){setMsg(error.message);setBusy(false);return}const rows=(data||[]).map((c:any,i:number)=>({"ID FOTO":photoId(i+1),Nombre:c.name,Categoría:c.categories?.name||"",Set:c.sets?.name||"",Número:c.card_number||"",Rareza:c.rarity||"",Idioma:c.language||"English",Condición:c.condition||"Near Mint","Precio MXN":Number(c.price),Stock:c.stock,Publicado:c.published?'Sí':'No',Ubicación:"",Notas:"",Imagen:c.image_url||""}));downloadRows(rows,`la-comarca-inventario-${new Date().toISOString().slice(0,10)}.xlsx`);setMsg(`Exportación lista: ${rows.length} producto(s).`);setBusy(false)}
 function downloadRows(rows:Row[],name:string){const ws=XLSX.utils.json_to_sheet(rows,{header:HEADERS});const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Inventario");XLSX.writeFile(wb,name)}
 function downloadTemplate(){const rows=Array.from({length:100},(_,i)=>({"ID FOTO":photoId(i+1),Nombre:"",Categoría:"",Set:"",Número:"",Rareza:"",Idioma:"English",Condición:"Near Mint","Precio MXN":"",Stock:"",Publicado:"Sí",Ubicación:"",Notas:"",Imagen:`fotos/${photoId(i+1)}.jpg`}));downloadRows(rows,"la-comarca-plantilla-inventario.xlsx");setMsg("Plantilla creada con 100 IDs de foto: LC-000001 a LC-000100.")}
 function validateRows(rows:Row[]){const errs:string[]=[];rows.forEach((r,i)=>{REQUIRED.forEach(k=>{if(r[k]===undefined||r[k]==="")errs.push(`Fila ${i+2}: falta ${k}.`)});if(r["Precio MXN"]!==""&&!Number.isFinite(Number(r["Precio MXN"])))errs.push(`Fila ${i+2}: Precio MXN inválido.`);if(r.Stock!==""&&(!Number.isInteger(Number(r.Stock))||Number(r.Stock)<0))errs.push(`Fila ${i+2}: Stock inválido.`);if(r["ID FOTO"]&&!/^LC-\\d{6}$/.test(String(r["ID FOTO"])))errs.push(`Fila ${i+2}: ID FOTO inválido.`)});return errs.slice(0,100)}
 async function readXlsx(file:File){try{const wb=XLSX.read(await file.arrayBuffer(),{type:'array'});const sheet=wb.Sheets['Inventario']||wb.Sheets[wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json<Row>(sheet,{defval:""});const errs=validateRows(rows);setRowsForImport(rows);setTotalRows(rows.length);setPreview(rows.slice(0,10));setErrors(errs);setPhotoCount(rows.filter(r=>r["ID FOTO"]).length);setMsg(errs.length?`Se detectaron ${errs.length} problema(s). Corrige el archivo antes de importar.`:`${rows.length} fila(s) listas para revisión.`)}catch(e:any){setErrors(['No se pudo leer el Excel: '+e.message]);setPreview([])}}
 async function readZip(file:File){setZipFile(file);setErrors([]);setMsg("");try{const zip=await JSZip.loadAsync(file);const xlsxEntry=Object.values(zip.files).find((f:any)=>!f.dir&&f.name.toLowerCase().endsWith('.xlsx'));if(!xlsxEntry)throw new Error('El ZIP debe contener un archivo .xlsx.');const xlsxData=await xlsxEntry.async('arraybuffer');const wb=XLSX.read(xlsxData,{type:'array'});const sheet=wb.Sheets['Inventario']||wb.Sheets[wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json<Row>(sheet,{defval:""});const errs=validateRows(rows);const names=new Set(Object.values(zip.files).filter((f:any)=>!f.dir&&/\.(jpg|jpeg|png|webp)$/i.test(f.name)).map((f:any)=>cleanPhotoName(f.name)));const missing:string[]=[];rows.forEach((r,i)=>{const id=cleanPhotoName(r["ID FOTO"]);const explicit=cleanPhotoName(r.Imagen);if(id&&!Array.from(names).some(n=>n===`${id}.jpg`||n===`${id}.jpeg`||n===`${id}.png`||n===`${id}.webp`)&&!names.has(explicit))missing.push(`Fila ${i+2}: no se encontró foto para ${r["ID FOTO"]}.`)});setRowsForImport(rows);setTotalRows(rows.length);setPreview(rows.slice(0,10));setPhotoCount(names.size);setErrors([...errs,...missing].slice(0,100));setMsg((errs.length||missing.length)?`Se detectaron ${errs.length+missing.length} problema(s). Corrige el ZIP antes de importar.`:`ZIP listo: ${rows.length} fila(s) y ${names.size} foto(s).`)}catch(e:any){setErrors(['No se pudo leer el ZIP: '+e.message]);setPreview([])}}
 async function importInventory(){if(!rowsForImport.length||errors.length)return;setBusy(true);setMsg("Preparando importación...");const {data:u}=await sb.auth.getUser();if(!u.user){router.replace('/login');return}let zip:JSZip|null=null;if(zipFile)zip=await JSZip.loadAsync(zipFile);const {data:cats}=await sb.from('categories').select('id,name');const {data:sets}=await sb.from('sets').select('id,name,code');const catMap=new Map((cats||[]).map((x:any)=>[String(x.name).trim().toLowerCase(),x.id]));const setMap=new Map<string,any>();(sets||[]).forEach((x:any)=>{setMap.set(String(x.name).trim().toLowerCase(),x.id);if(x.code)setMap.set(String(x.code).trim().toLowerCase(),x.id)});let created=0,rejected=0,photos=0;const details:any[]=[];for(let i=0;i<rowsForImport.length;i++){const r=rowsForImport[i];try{const categoryId=catMap.get(String(r["Categoría"]).trim().toLowerCase());if(!categoryId)throw new Error(`Categoría no encontrada: ${r["Categoría"]}`);const setId=r.Set?setMap.get(String(r.Set).trim().toLowerCase())||null:null;let image_url:string|null=null;const wanted=cleanPhotoName(r["ID FOTO"]);if(zip&&wanted){const entry=Object.values(zip.files).find((f:any)=>!f.dir&&cleanPhotoName(f.name).match(new RegExp(`^${wanted}\\.(jpg|jpeg|png|webp)$`,'i')));if(entry){const blob=await entry.async('blob');const ext=(entry.name.match(/\.(jpg|jpeg|png|webp)$/i)?.[1]||'jpg').toLowerCase();const path=`inventory/${u.user.id}/${wanted}.${ext}`;const {error}=await sb.storage.from('card-images').upload(path,blob,{upsert:true,contentType:blob.type||`image/${ext==='jpg'?'jpeg':ext}`});if(error)throw error;image_url=sb.storage.from('card-images').getPublicUrl(path).data.publicUrl;photos++}}else if(r.Imagen&&/^https?:\\/\\//i.test(String(r.Imagen)))image_url=String(r.Imagen).trim();const payload={name:String(r.Nombre).trim(),category_id:categoryId,set_id:setId,card_number:r.Número?String(r.Número):null,rarity:r.Rareza?String(r.Rareza):null,language:String(r.Idioma||'English'),condition:String(r.Condición||'Near Mint'),price:Number(r["Precio MXN"]),stock:Number(r.Stock),published:String(r.Publicado||'Sí').toLowerCase()==='sí',image_url,created_by:u.user.id,updated_by:u.user.id};const {error}=await sb.from('cards').insert(payload);if(error)throw error;created++}catch(e:any){rejected++;details.push({row:i+2,error:e.message||String(e)})}}setMsg(`Importación terminada: ${created} creados, ${rejected} rechazados, ${photos} fotos asociadas.`);setBusy(false);setErrors(details.map(d=>`Fila ${d.row}: ${d.error}`).slice(0,100));setPreview([])}
 return <><header className="top"><a href="/admin">← Administración</a><b>La Comarca · Inventario</b><div className="actions"><button className="btn2" onClick={exportXlsx}>⬇ Exportar XLSX</button><button className="btn2" onClick={()=>router.push('/catalogo')}>Catálogo</button></div></header><main className="wrap"><div className="panel"><h2>Importar inventario</h2><p className="muted">Acceso: {role}. Puedes cargar un Excel solo o un ZIP con Excel + fotos.</p><div className="actions"><button className="btn2" onClick={downloadTemplate}>📄 Descargar plantilla Excel</button><label className="btn2" style={{cursor:'pointer'}}>📥 Seleccionar Excel<input hidden type="file" accept=".xlsx" onChange={e=>{const f=e.target.files?.[0];if(f){setZipFile(null);readXlsx(f)}}}/></label><label className="btn2" style={{cursor:'pointer'}}>📦 Seleccionar ZIP con fotos<input hidden type="file" accept=".zip" onChange={e=>{const f=e.target.files?.[0];if(f)readZip(f)}}/></label></div><p className="muted">Formato ZIP: <b>inventario.xlsx</b> + carpeta <b>fotos/</b>. Las fotos se nombran con el ID FOTO: <b>LC-000001.jpg</b>.</p>{totalRows>0&&<p>{totalRows} fila(s) · {photoCount} foto(s) detectadas.</p>}{errors.length>0&&<div className="notice">{errors.map((e,i)=><div key={i}>{e}</div>)}</div>}{totalRows>0&&!errors.length&&<div className="notice">✓ Archivo válido. Vista previa de hasta 10 filas.</div>}{totalRows>0&&!errors.length&&<button className="btn" disabled={busy} onClick={importInventory}>{busy?'Importando...':'Confirmar importación'}</button>}{msg&&<p className="notice">{msg}</p>}</div>{preview.length>0&&<div className="panel"><h3>Vista previa</h3><div style={{overflow:'auto'}}><table className="table"><thead><tr>{Object.keys(preview[0]).map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{preview.map((r,i)=><tr key={i}>{Object.keys(preview[0]).map(k=><td key={k}>{String(r[k]??'')}</td>)}</tr>)}</tbody></table></div></div>}<div className="panel"><h3>Cómo preparar las fotos</h3><ol><li>Descarga la plantilla; ya incluye IDs como <b>LC-000001</b>.</li><li>Toma cada foto y nómbrala con su ID, por ejemplo <b>LC-000001.jpg</b>.</li><li>Guarda las fotos dentro de una carpeta <b>fotos/</b>.</li><li>Comprime el Excel y la carpeta en un ZIP y súbelo aquí.</li></ol><p className="muted">También puedes usar una URL en la columna Imagen.</p></div></main></>;
}