"use client";
import {useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {supabaseBrowser} from "../../../lib/supabase";

type Cat={id:string;name:string}; type Card={id:string;name:string;price:number;stock:number}; type Join={card_id:string;category_id:string}; type Item={card_id:string;quantity:number;unit_price:number;order_id:string}; type Order={id:string;status:string;created_at:string}; type Audit={id:string;card_id:string|null;agent_id:string|null;action:string;created_at:string;old_value:any;new_value:any};
export default function Metrics(){const sb=supabaseBrowser(),router=useRouter();const [cats,setCats]=useState<Cat[]>([]),[cards,setCards]=useState<Card[]>([]),[joins,setJoins]=useState<Join[]>([]),[items,setItems]=useState<Item[]>([]),[orders,setOrders]=useState<Order[]>([]),[audits,setAudits]=useState<Audit[]>([]),[names,setNames]=useState<Record<string,string>>({}),[days,setDays]=useState(30),[loading,setLoading]=useState(true),[error,setError]=useState("");
useEffect(()=>{(async()=>{try{const {data:u,error:authError}=await sb.auth.getUser();if(authError)throw authError;if(!u.user){router.replace('/login');return}const {data:p,error:profileError}=await sb.from('profiles').select('role').eq('id',u.user.id).maybeSingle();if(profileError)throw profileError;if(p?.role!=="admin"){router.replace('/login');return}}catch(e:any){setError(e?.message||"No fue posible verificar el acceso.");setLoading(false)}})()},[router,sb]);
async function load(){setLoading(true);setError("");try{const since=new Date(Date.now()-days*86400000).toISOString();const [c,ca,j,oi,o,a,pr]=await Promise.all([sb.from('categories').select('id,name').order('name'),sb.from('cards').select('id,name,price,stock'),sb.from('card_categories').select('card_id,category_id'),sb.from('order_items').select('card_id,quantity,unit_price,order_id'),sb.from('orders').select('id,status,created_at').gte('created_at',since),sb.from('inventory_audit_log').select('id,card_id,agent_id,action,created_at,old_value,new_value').gte('created_at',since).order('created_at',{ascending:false}).limit(100),sb.from('profiles').select('id,email')]);const e=[c.error,ca.error,j.error,oi.error,o.error,a.error,pr.error].find(Boolean);if(e)throw e;setCats(c.data||[]);setCards(ca.data||[]);setJoins(j.data||[]);setItems(oi.data||[]);setOrders(o.data||[]);setAudits(a.data||[]);const map:Record<string,string>={};(pr.data||[]).forEach((x:any)=>{if(x?.id)map[x.id]=x.email||x.id});setNames(map)}catch(e:any){setError(e?.message||"No fue posible cargar las métricas.")}finally{setLoading(false)}}
useEffect(()=>{let active=true;(async()=>{try{const {data:u}=await sb.auth.getUser();if(!u.user||!active)return;const {data:p}=await sb.from('profiles').select('role').eq('id',u.user.id).maybeSingle();if(p?.role!=="admin"||!active)return;await load()}catch(e:any){if(active){setError(e?.message||"No fue posible cargar las métricas.");setLoading(false)}}})();return()=>{active=false}},[days]);
const validOrders=new Set(orders.filter(o=>!['cancelled'].includes(o.status)).map(o=>o.id));const rows=useMemo(()=>cats.map(cat=>{const ids=new Set(joins.filter(j=>j.category_id===cat.id).map(j=>j.card_id));const cs=cards.filter(c=>ids.has(c.id));const sold=items.filter(i=>ids.has(i.card_id)&&validOrders.has(i.order_id));const units=sold.reduce((s,i)=>s+i.quantity,0);const sales=sold.reduce((s,i)=>s+Number(i.unit_price)*i.quantity,0);return {cat,products:cs.length,stock:cs.reduce((s,c)=>s+c.stock,0),inventory:cs.reduce((s,c)=>s+Number(c.price)*c.stock,0),units,sales,ticket:units?sales/units:0}}),[cats,cards,joins,items,orders]);
const totals=rows.reduce((a,r)=>({products:a.products+r.products,stock:a.stock+r.stock,inventory:a.inventory+r.inventory,units:a.units+r.units,sales:a.sales+r.sales}),{products:0,stock:0,inventory:0,units:0,sales:0});const cardNames=Object.fromEntries(cards.map(c=>[c.id,c.name]));
return <><header className="top"><a href="/admin">← Administración</a><b>La Comarca · Métricas</b><div className="actions"><button className="btn2" onClick={load} disabled={loading}>↻ Actualizar</button><a href="/admin/orders">Pedidos</a></div></header><main className="wrap"><div className="panel"><div className="row"><div><h2>Ventas por categoría</h2><p className="muted">Inventario, ventas y unidades vendidas por periodo.</p></div><div><label>Periodo</label><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value="7">7 días</option><option value="30">30 días</option><option value="90">90 días</option><option value="365">365 días</option></select></div></div>{error&&<div className="notice" style={{border:'1px solid #dc2626'}}>⚠️ Error al cargar: {error}</div>}<div className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))'}}>{[["Productos",totals.products],["Unidades en stock",totals.stock],["Valor inventario",`$${totals.inventory.toLocaleString('es-MX',{maximumFractionDigits:0})}`],["Unidades vendidas",totals.units],["Ventas",`$${totals.sales.toLocaleString('es-MX',{maximumFractionDigits:0})}`]].map(x=><div className="panel" key={String(x[0])}><div className="muted">{x[0]}</div><div className="price">{x[1]}</div></div>)}</div></div><div className="panel"><h2>Desempeño por categoría</h2>{loading?<div className="empty">Cargando métricas...</div>:<div style={{overflow:'auto'}}><table className="table"><thead><tr><th>Categoría</th><th>Productos</th><th>Stock</th><th>Inventario</th><th>Unidades vendidas</th><th>Ventas</th><th>Precio medio</th></tr></thead><tbody>{rows.map(r=><tr key={r.cat.id}><td><b>{r.cat.name}</b></td><td>{r.products}</td><td>{r.stock}</td><td>${r.inventory.toLocaleString('es-MX',{maximumFractionDigits:0})}</td><td>{r.units}</td><td>${r.sales.toLocaleString('es-MX',{maximumFractionDigits:0})}</td><td>${r.ticket.toLocaleString('es-MX',{maximumFractionDigits:0})}</td></tr>)}</tbody></table></div>}</div><div className="panel"><h2>Actividad de agentes</h2><p className="muted">Últimos movimientos de inventario del periodo seleccionado.</p>{audits.length===0?<div className="empty">Sin movimientos registrados en este periodo.</div>:<div style={{overflow:'auto'}}><table className="table"><thead><tr><th>Fecha</th><th>Agente</th><th>Acción</th><th>Producto</th><th>Cambio</th></tr></thead><tbody>{audits.map(a=><tr key={a.id}><td>{new Date(a.created_at).toLocaleString('es-MX')}</td><td>{a.agent_id?(names[a.agent_id]||a.agent_id.slice(0,8)):'Sistema'}</td><td>{a.action}</td><td>{a.card_id?(cardNames[a.card_id]||a.card_id.slice(0,8)):'—'}</td><td className="muted">{a.new_value?JSON.stringify(a.new_value):''}</td></tr>)}</tbody></table></div>}</div></main></>}
