"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import Link from "next/link";
import {supabaseBrowser} from "../../lib/supabase";

export default function Registro(){
 const router=useRouter(); const [form,setForm]=useState({name:"",email:"",password:"",phone:"",recipient:"",street:"",number:"",interior:"",neighborhood:"",city:"",municipality:"",state:"",postal:"",references:""}); const [err,setErr]=useState(""); const [busy,setBusy]=useState(false);
 const set=(k:string,v:string)=>setForm(f=>({...f,[k]:v}));
 async function submit(e:any){e.preventDefault();setBusy(true);setErr("");const sb=supabaseBrowser();const {data,error}=await sb.auth.signUp({email:form.email,password:form.password});if(error){setErr(error.message);setBusy(false);return}if(!data.user){setErr("No fue posible crear la cuenta.");setBusy(false);return}const {error:profileError}=await sb.from("customer_accounts").insert({id:data.user.id,full_name:form.name,phone:form.phone,email:form.email,shipping_recipient:form.recipient,shipping_street:form.street,shipping_number:form.number,shipping_interior:form.interior,shipping_neighborhood:form.neighborhood,shipping_city:form.city,shipping_municipality:form.municipality,shipping_state:form.state,shipping_postal_code:form.postal,shipping_references:form.references,membership_tier:"cliente",membership_price:150,membership_status:"pendiente"});if(profileError){await sb.auth.signOut();setErr(profileError.message);setBusy(false);return}router.push("/cuenta");}
 return <main className="wrap"><div className="panel"><h1>Crear cuenta</h1><p className="muted">Cuenta de cliente La Comarca. La activación requiere una membresía de $150 MXN, reembolsable en tienda.</p><form onSubmit={submit}><h2>Datos personales</h2><label>Nombre completo</label><input required value={form.name} onChange={e=>set("name",e.target.value)}/><label>Correo electrónico</label><input required type="email" value={form.email} onChange={e=>set("email",e.target.value)}/><label>Contraseña</label><input required minLength={8} type="password" value={form.password} onChange={e=>set("password",e.target.value)}/><label>Teléfono</label><input required value={form.phone} onChange={e=>set("phone",e.target.value)}/><h2>Datos de envío</h2><label>Destinatario</label><input required value={form.recipient} onChange={e=>set("recipient",e.target.value)}/><label>Calle</label><input required value={form.street} onChange={e=>set("street",e.target.value)}/><label>Número</label><input required value={form.number} onChange={e=>set("number",e.target.value)}/><label>Interior</label><input value={form.interior} onChange={e=>set("interior",e.target.value)}/><label>Colonia</label><input required value={form.neighborhood} onChange={e=>set("neighborhood",e.target.value)}/><label>Ciudad</label><input required value={form.city} onChange={e=>set("city",e.target.value)}/><label>Municipio</label><input required value={form.municipality} onChange={e=>set("municipality",e.target.value)}/><label>Estado</label><input required value={form.state} onChange={e=>set("state",e.target.value)}/><label>Código postal</label><input required value={form.postal} onChange={e=>set("postal",e.target.value)}/><label>Referencias</label><textarea value={form.references} onChange={e=>set("references",e.target.value)}/><div className="notice">Membresía inicial: <b>$150 MXN</b>. Reembolsable en tienda y sujeta a activación por La Comarca.</div><button className="btn" style={{width:"100%",marginTop:14}} disabled={busy}>{busy?"Creando cuenta...":"Crear cuenta"}</button></form>{err&&<p className="notice">{err}</p>}<p className="muted" style={{marginTop:16}}>¿Ya tienes cuenta? <Link href="/login">Inicia sesión</Link></p></div></main>;
}
