"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabaseBrowser } from "../../lib/supabase";
const labels:any={pending:"Pendiente",contacted:"Contactado",paid:"Pagado",preparing:"Preparando",shipped:"Enviado",completed:"Completado",cancelled:"Cancelado"};
export default function Operativo(){
 const sb=supabaseBrowser(),router=useRouter(); const [role,setRole]=useState(""),[orders,setOrders]=useState<any[]>([]),[notes,setNotes]=useState<Record<string,string>>({}),[existingNotes,setExistingNotes]=useState<Record<string,any[]>>({}),[alerts,setAlerts]=useState<any[]>([]),[alertText,setAlertText]=useState<Record<string,string>>({}),[msg,setMsg]=useState("");
 async function load(){const {data}=await sb.from("orders").select("id,customer_name,status,total,created_at,tracking_carrier,tracking_number").order("created_at",{ascending:false});setOrders(data||[]);const ids=(data||[]).map((o:any)=>o.id);if(ids.length){const {data:n}=await sb.from("order_notes").select("id,order_id,body,created_at,created_by").in("order_id",ids).order("created_at",{ascending:false});const grouped:any={};(n||[]).forEach((x:any)=>(grouped[x.order_id]??=[]).push(x));setExistingNotes(grouped)}else setExistingNotes({});const {data:a}=await sb.from("order_alerts").select("*").order("created_at",{ascending:false});setAlerts(a||[])}
 useEffect(()=>{(async()=>{const {data:{user}}=await sb.auth.getUser();if(!user){router.replace('/login');return}const {data:p}=await sb.from('profiles').select('role').eq('id',user.id).maybeSingle();if(!p||!['admin','agent'].includes(p.role)){router.replace('/login');return}setRole(p.role);load()})()},[]);
 async function addNote(id:string){const text=(notes[id]||'').trim();if(!text)return;const {data:{user}}=await sb.auth.getUser();const {error}=await sb.from('order_notes').insert({order_id:id,body:text,created_by:user?.id});if(error)setMsg(error.message);else{setNotes({...notes,[id]:''});setMsg('Nota guardada.');load()}}
 async function addAlert(id:string){const text=(alertText[id]||'').trim();if(!text)return;const {data:{user}}=await sb.auth.getUser();const {error}=await sb.from('order_alerts').insert({order_id:id,body:text,created_by:user?.id,status:'open'});if(error)setMsg(error.message);else{setAlertText({...alertText,[id]:''});setMsg('Alerta enviada al administrador.');load()}}
 async function resolve(id:string){const {error}=await sb.from('order_alerts').update({status:'resolved',resolved_at:new Date().toISOString()}).eq('id',id);if(error)setMsg(error.message);else load()}
 return <><header className="top"><a href="/admin">← Administración</a><b>Panel Operativo</b><a href="/catalogo">Catálogo</a></header><main className="wrap"><div className="panel"><h1>Panel Operativo</h1><p className="muted">Rol: {role}. Los agentes pueden consultar pedidos, agregar notas y enviar alertas; no pueden cambiar estados, pagos, inventario ni tracking.</p>{msg&&<div className="notice">{msg}</div>}</div><div className="panel"><h2>🚨 Alertas</h2>{alerts.length===0?<p className="muted">Sin alertas.</p>:alerts.map(a=><div key={a.id} className="notice" style={{margin:'10px 0'}}><b>{a.status==='open'?'🔴 Pendiente':'🟢 Resuelta'}</b> · Pedido {a.order_id.slice(0,8).toUpperCase()}<div>{a.body}</div>{role==='admin'&&a.status==='open'&&<button className="btn" onClick={()=>resolve(a.id)}>Resolver</button>}</div>)}</div><div className="panel"><h2>📦 Pedidos</h2>{orders.map(o=><article key={o.id} className="panel" style={{margin:'12px 0'}}><b>#{o.id.slice(0,8).toUpperCase()} · {o.customer_name||'Cliente'}</b><div className="muted">{labels[o.status]||o.status} · ${Number(o.total).toLocaleString('es-MX')} MXN</div>{o.tracking_number&&<div className="notice">📦 {o.tracking_carrier||'Paquetería'} · {o.tracking_number}</div>}<details style={{marginTop:10}}><summary>Notas del equipo ({(existingNotes[o.id]||[]).length})</summary>{(existingNotes[o.id]||[]).map((n:any)=><div key={n.id} className="muted" style={{padding:'7px 0'}}>{n.body} · {new Date(n.created_at).toLocaleString('es-MX')}</div>)}</details><label>Nota operativa</label><textarea value={notes[o.id]||''} onChange={e=>setNotes({...notes,[o.id]:e.target.value})} placeholder="Escribe una nota para el equipo..."/><button className="btn2" onClick={()=>addNote(o.id)}>Guardar nota</button><label style={{marginTop:10}}>Alerta al admin</label><textarea value={alertText[o.id]||''} onChange={e=>setAlertText({...alertText,[o.id]:e.target.value})} placeholder="Algo requiere atención..."/><button className="btn2" onClick={()=>addAlert(o.id)}>🚨 Enviar alerta</button></article>)}</div></main></>}
