"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {supabaseBrowser} from "../../../lib/supabase";

type Permission={agent_id:string;category_id:string;can_view:boolean;can_create:boolean;can_edit:boolean;can_change_price:boolean;can_change_stock:boolean;can_manage_tags:boolean;can_publish:boolean;can_delete:boolean};
const empty=(agent_id:string,category_id:string):Permission=>({agent_id,category_id,can_view:true,can_create:false,can_edit:false,can_change_price:false,can_change_stock:false,can_manage_tags:false,can_publish:false,can_delete:false});
const actions:[keyof Permission,string][]=[['can_view','Ver'],['can_create','Crear'],['can_edit','Editar'],['can_change_price','Precio'],['can_change_stock','Stock'],['can_manage_tags','Etiquetas'],['can_publish','Publicar'],['can_delete','Eliminar']];
export default function Permissions(){const router=useRouter();const sb=supabaseBrowser();const [agents,setAgents]=useState<any[]>([]),[categories,setCategories]=useState<any[]>([]),[perms,setPerms]=useState<Record<string,Permission>>({}),[selected,setSelected]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(''),[msg,setMsg]=useState('');
useEffect(()=>{(async()=>{const {data:user}=await sb.auth.getUser();if(!user.user){router.replace('/login');return}const {data:profile}=await sb.from('profiles').select('role').eq('id',user.user.id).maybeSingle();if(profile?.role!=='admin'){await sb.auth.signOut();router.replace('/login');return}const [{data:a},{data:c},{data:p}]=await Promise.all([sb.from('profiles').select('id,role').eq('role','agent').order('created_at'),sb.from('categories').select('id,name').order('name'),sb.from('agent_category_permissions').select('*')]);setAgents(a||[]);setCategories(c||[]);const map:Record<string,Permission>={};(p||[]).forEach((x:any)=>{map[`${x.agent_id}:${x.category_id}`]=x});setPerms(map);if(a?.[0])setSelected(a[0].id);setLoading(false)})()},[]);
function get(agent:string,cat:string){return perms[`${agent}:${cat}`]||empty(agent,cat)}
function toggle(agent:string,cat:string,key:keyof Permission){const p=get(agent,cat);setPerms({...perms,[`${agent}:${cat}`]:{...p,[key]:!p[key]}})}
async function save(agent:string,cat:string){setSaving(`${agent}:${cat}`);setMsg('');const p=get(agent,cat);const {error}=await sb.from('agent_category_permissions').upsert(p,{onConflict:'agent_id,category_id'});if(error)setMsg(error.message);else setMsg('Permiso actualizado.');setSaving('')}
async function remove(agent:string,cat:string){setSaving(`${agent}:${cat}`);const {error}=await sb.from('agent_category_permissions').delete().eq('agent_id',agent).eq('category_id',cat);if(!error){const next={...perms};delete next[`${agent}:${cat}`];setPerms(next);setMsg('Categoría retirada del agente.')}else setMsg(error.message);setSaving('')}
if(loading)return <main className="wrap"><div className="empty">Cargando permisos...</div></main>;
const visible=selected?categories:[];return <><header className="top"><a href="/admin">← Administración</a><b>Permisos por categoría</b><a href="/pokemon">Catálogo</a></header><main className="wrap"><div className="panel"><h2>Acceso de agentes</h2><p className="muted">El administrador decide qué categorías puede ver cada agente y qué acciones puede realizar. La restricción también se aplica en Supabase, no solo en la interfaz.</p>{agents.length===0?<div className="notice">No hay usuarios con rol <b>agent</b>. Cuando existan, aparecerán aquí para asignarles categorías.</div>:<><label>Agente</label><select value={selected} onChange={e=>setSelected(e.target.value)}>{agents.map(a=><option key={a.id} value={a.id}>{a.id}</option>)}</select></>}</div>{selected&&<div className="panel"><h2>Categorías</h2><div style={{overflow:'auto'}}><table className="table"><thead><tr><th>Categoría</th>{actions.map(([,label])=><th key={label}>{label}</th>)}<th>Guardar</th></tr></thead><tbody>{visible.map(c=>{const p=get(selected,c.id);const assigned=Boolean(perms[`${selected}:${c.id}`]);return <tr key={c.id}><td><b>{c.name}</b><br/><span className="muted">{assigned?'Asignada':'Oculta para este agente'}</span></td>{actions.map(([key,label])=><td key={label}><input aria-label={`${c.name} ${label}`} type="checkbox" checked={Boolean(p[key])} onChange={()=>toggle(selected,c.id,key)} /></td>)}<td><div className="actions"><button className="btn" disabled={saving===`${selected}:${c.id}`} onClick={()=>save(selected,c.id)}>{saving===`${selected}:${c.id}`?'...':'Guardar'}</button>{assigned&&<button className="danger" disabled={saving===`${selected}:${c.id}`} onClick={()=>remove(selected,c.id)}>Ocultar</button>}</div></td></tr>})}</tbody></table></div></div>}{msg&&<div className="panel notice">{msg}</div>}<div className="panel"><h3>Regla de seguridad</h3><p className="muted">Si una categoría no está asignada al agente, no podrá verla en el panel ni consultar o modificar sus productos mediante una petición directa. Los permisos de precio, stock, etiquetas, publicación y eliminación son independientes.</p></div></main></>}
