"use client";
import { useMemo,useState,useEffect } from "react";
import { supabaseBrowser } from "../lib/supabase";
declare global { interface Window { XLSX?: any } }
type Card={id:string;name:string;category_id:string|null;set_id:string|null;card_number:string|null;rarity:string|null;language:string;condition:string;image_url:string|null;price:number;stock:number;published:boolean;categories?:{name:string}|null;sets?:{name:string;code?:string|null}|null};
type Ref={id:string;name:string;code?:string|null};
const columns=["ID","Nombre","Categoría","Set","Código Set","Número","Rareza","Idioma","Condición","Precio MXN","Stock","Publicada","Imagen URL"];
const clean=(v:unknown)=>String(v??"").trim();const bool=(v:unknown)=>["true","sí","si","yes","1","publicado"].includes(clean(v).toLowerCase());
export default function ExcelCatalog(){const[file,setFile]=useState<File|null>(null),[rows,setRows]=useState<Record<string,unknown>[]>([]),[status,setStatus]=useState(""),[busy,setBusy]=useState(false),[xlsxReady,setXlsxReady]=useState(false);const sb=useMemo(()=>supabaseBrowser(),[]);
useEffect(()=>{if(window.XLSX){setXlsxReady(true);return}const s=document.createElement("script");s.src="https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js";s.onload=()=>setXlsxReady(true);s.onerror=()=>setStatus("No se pudo cargar el motor Excel.");document.head.appendChild(s)},[]);const xlsx=()=>window.XLSX;
async function exportCatalog(){if(!xlsxReady)return;setBusy(true);setStatus("");const{data,error}=await sb.from("cards").select("*,categories(name),sets(name,code)").order("name");if(error){setStatus(error.message);setBusy(false);return}const output=(data||[]).map((c:Card)=>({"ID":c.id,"Nombre":c.name,"Categoría":c.categories?.name||"","Set":c.sets?.name||"","Código Set":c.sets?.code||"","Número":c.card_number||"","Rareza":c.rarity||"","Idioma":c.language||"English","Condición":c.condition||"Near Mint","Precio MXN":Number(c.price||0),"Stock":Number(c.stock||0),"Publicada":c.published?"Sí":"No","Imagen URL":c.image_url||""}));const wb=xlsx().utils.book_new(),ws=xlsx().utils.json_to_sheet(output,{header:columns});ws["!cols"]=columns.map(x=>({wch:Math.max(12,x.length+2)}));xlsx().utils.book_append_sheet(wb,ws,"Catalogo");xlsx().writeFile(wb,`la-comarca-catalogo-${new Date().toISOString().slice(0,10)}.xlsx`);setStatus(`${output.length} productos exportados.`);setBusy(false)}
function template(){if(!xlsxReady)return;const wb=xlsx().utils.book_new(),ws=xlsx().utils.aoa_to_sheet([columns,["","Ejemplo","","","","","","English","Near Mint",0,0,"Sí",""]]);xlsx().utils.book_append_sheet(wb,ws,"Plantilla");xlsx().writeFile(wb,"la-comarca-plantilla.xlsx")}
function parseFile(f:File){if(!xlsxReady){setStatus("El motor Excel aún está cargando.");return}setFile(f);setStatus("");const reader=new FileReader();reader.onload=e=>{try{const wb=xlsx().read(e.target?.result,{type:"array"}),ws=wb.Sheets[wb.SheetNames[0]],data=xlsx().utils.sheet_to_json(ws,{defval:""}) as Record<string,unknown>[];setRows(data);setStatus(`${data.length} filas listas para importar.`)}catch{setRows([]);setStatus("No se pudo leer el archivo Excel.")}};reader.readAsArrayBuffer(f)}
async function importCatalog(){if(!rows.length)return;setBusy(true);setStatus("Validando catálogo...");const[{data:categories},{data:sets},{data:existing,error:existingError},{data:auth}]=await Promise.all([sb.from("categories").select("id,name"),sb.from("sets").select("id,name,code"),sb.from("cards").select("*,categories(name),sets(name,code)"),sb.auth.getUser()]);if(existingError||!auth.user){setStatus(existingError?.message||"Sesión no válida.");setBusy(false);return}const catMap=new Map<string,Ref>((categories||[]).map((x:Ref)=>[x.name.toLowerCase(),x])),setMap=new Map<string,Ref>();(sets||[]).forEach((x:Ref)=>{setMap.set(x.name.toLowerCase(),x);if(x.code)setMap.set(x.code.toLowerCase(),x)});const byId=new Map<string,Card>((existing||[]).map((x:Card)=>[x.id,x])),byKey=new Map<string,Card>();(existing||[]).forEach((x:Card)=>byKey.set(`${x.name.toLowerCase()}|${x.set_id||""}|${x.card_number||""}`,x));let created=0,updated=0,errors=0;const messages:string[]=[];
for(let i=0;i<rows.length;i++){const r=rows[i],name=clean(r["Nombre"]);if(!name){errors++;messages.push(`Fila ${i+2}: falta Nombre.`);continue}const category=catMap.get(clean(r["Categoría"]).toLowerCase());if(!category){errors++;messages.push(`Fila ${i+2}: categoría no encontrada (${clean(r["Categoría"])}).`);continue}const setValue=clean(r["Set"])||clean(r["Código Set"]),set=setValue?setMap.get(setValue.toLowerCase()):null;if(setValue&&!set){errors++;messages.push(`Fila ${i+2}: set no encontrado (${setValue}).`);continue}const price=Number(r["Precio MXN"]),stock=Number(r["Stock"]);if(!Number.isFinite(price)||price<0||!Number.isInteger(stock)||stock<0){errors++;messages.push(`Fila ${i+2}: precio o stock inválido.`);continue}const payload={name,category_id:category.id,set_id:set?.id||null,card_number:clean(r["Número"])||null,rarity:clean(r["Rareza"])||null,language:clean(r["Idioma"])||"English",condition:clean(r["Condición"])||"Near Mint",price,stock,published:bool(r["Publicada"]),image_url:clean(r["Imagen URL"])||null,updated_by:auth.user.id};const id=clean(r["ID"]),target=(id&&byId.get(id))||byKey.get(`${name.toLowerCase()}|${set?.id||""}|${payload.card_number||""}`);const result=target?await sb.from("cards").update(payload).eq("id",target.id).select().single():await sb.from("cards").insert({...payload,created_by:auth.user.id}).select().single();if(result.error||!result.data){errors++;messages.push(`Fila ${i+2}: ${result.error?.message||"no se pudo guardar"}`);continue}await sb.from("inventory_audit_log").insert({card_id:result.data.id,agent_id:auth.user.id,action:target?"excel_import_update":"excel_import_create",old_value:target||null,new_value:result.data});target?updated++:created++;if(!target)byId.set(result.data.id,result.data as Card)}setStatus(`Importación terminada: ${created} nuevos · ${updated} actualizados · ${errors} con errores.${messages.length?` ${messages.slice(0,3).join(" ")}`:""}`);setBusy(false);setRows([]);setFile(null)}
return <div className="panel" style={{marginBottom:18}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div><h2 style={{marginBottom:4}}>Excel · Catálogo</h2><div className="muted">Exporta, modifica en Excel y vuelve a importar para crear o actualizar productos.</div></div><div className="actions"><button className="btn2" onClick={exportCatalog} disabled={busy||!xlsxReady}>📤 Exportar Excel</button><button className="btn2" onClick={template} disabled={busy||!xlsxReady}>📄 Descargar plantilla</button></div></div><div style={{marginTop:14,display:"flex",gap:10,alignItems:"center",flexWrap:"wrap"}}><input type="file" accept=".xlsx,.xls" onChange={e=>{const f=e.target.files?.[0];if(f)parseFile(f)}} disabled={busy||!xlsxReady}/><button className="btn" onClick={importCatalog} disabled={busy||!rows.length}>📥 Importar {rows.length?`(${rows.length})`:"Excel"}</button></div>{file&&rows.length>0&&<div className="notice" style={{marginTop:12}}>Vista previa: <b>{file.name}</b> · {rows.length} filas. Actualiza por ID cuando existe; si no, usa Nombre + Set + Número.</div>}{status&&<p style={{marginBottom:0}}>{status}</p>}</div>}
