"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {supabaseBrowser} from "../../lib/supabase";

type Account={id:string;full_name:string;phone:string;email:string;shipping_recipient:string;shipping_street:string;shipping_number:string;shipping_interior:string;shipping_neighborhood:string;shipping_city:string;shipping_state:string;shipping_postal_code:string;shipping_references:string;membership_tier:string;membership_status:string};
type Movement={movement_date:string;concept:string;amount:number;balance_after:number};
type Request={id:string;request_type:string;status:string;notes:string|null};
const disclaimer=`La información mostrada en esta cuenta es informativa y está sujeta a los registros internos de La Comarca. Los saldos, movimientos, membresías, valuaciones y solicitudes pueden estar sujetos a revisión y validación. Los datos personales y de envío serán tratados de forma confidencial y utilizados para la prestación y administración de los servicios de La Comarca. La activación de una cuenta o membresía no implica la aceptación automática de artículos para venta o cambio.`;
export default function Cuenta(){const router=useRouter();const sb=supabaseBrowser();const[account,setAccount]=useState<Account|null>(null),[movements,setMovements]=useState<Movement[]>([]),[requests,setRequests]=useState<Request[]>([]),[msg,setMsg]=useState(""),[loading,setLoading]=useState(true),[requesting,setRequesting]=useState(false);
useEffect(()=>{(async()=>{const{data:u}=await sb.auth.getUser();if(!u.user){router.replace('/acceso');return}const{data:a}=await sb.from('customer_accounts').select('*').eq('id',u.user.id).maybeSingle();if(!a){setMsg('Tu cuenta aún no ha sido activada en el sistema.');setLoading(false);return}setAccount(a);const[{data:m},{data:r}]=await Promise.all([sb.from('account_movements').select('movement_date,concept,amount,balance_after').eq('customer_id',a.id).order('movement_date',{ascending:false}),sb.from('plus_requests').select('id,request_type,status,notes').eq('customer_id',a.id).order('created_at',{ascending:false})]);setMovements(m||[]);setRequests(r||[]);setLoading(false)})()},[]);
async function request(type:'venta'|'cambio'){if(!account||account.membership_tier!=='plus'||account.membership_status!=='active')return;setRequesting(true);const{error}=await sb.from('plus_requests').insert({customer_id:account.id,request_type:type,status:'pendiente_llamada',notes:'El cliente solicita llamada previa con su agente antes de enviar coleccionables.'});setMsg(error?'No se pudo registrar la solicitud.':'Solicitud registrada. Un agente se pondrá en contacto contigo.');if(!error){const{data:r}=await sb.from('plus_requests').select('id,request_type,status,notes').eq('customer_id',account.id).order('created_at',{ascending:false});setRequests(r||[])}setRequesting(false)}
async function logout(){await sb.auth.signOut();router.push('/acceso')}
if(loading)return <main className="wrap"><div className="empty">Cargando cuenta...</div></main>;
if(!account)return <><header className="top"><b>La Comarca</b><div className="actions"><a className="btn2" href="/catalogo">Catálogo</a><button className="btn2" onClick={logout}>Salir</button></div></header><main className="wrap"><div className="panel"><h1>Mi cuenta</h1><p>{msg}</p></div></main></>;
const plus=account.membership_tier==='plus';return <><header className="top"><a href="/">La Comarca</a><b>Mi cuenta</b><div className="actions"><a className="btn2" href="/catalogo">Catálogo</a><button className="btn2" onClick={logout}>Salir</button></div></header><main className="wrap"><div className="panel"><h1>Mi cuenta</h1><div className="notice"><b>{plus?'⭐ Cliente Plus':'Cliente'}</b> · {account.membership_status==='active'?'Cuenta activa':'Membresía pendiente'}</div><h2>Datos de contacto</h2><p><b>{account.full_name}</b><br/>📧 {account.email}<br/>📱 {account.phone}</p><h2>Datos de envío</h2><p>{account.shipping_recipient}<br/>{account.shipping_street} {account.shipping_number}{account.shipping_interior?` Int. ${account.shipping_interior}`:''}<br/>{account.shipping_neighborhood}<br/>{account.shipping_postal_code}, {account.shipping_city}, {account.shipping_state}<br/>{account.shipping_references&&<>Ref.: {account.shipping_references}</>}</p><h2>Movimientos de cuenta</h2>{movements.length?<div style={{overflow:'auto'}}><table className="table"><thead><tr><th>Fecha</th><th>Concepto</th><th>Movimiento</th><th>Saldo</th></tr></thead><tbody>{movements.map((m,i)=><tr key={i}><td>{new Date(m.movement_date).toLocaleDateString('es-MX')}</td><td>{m.concept}</td><td>{Number(m.amount)>=0?'+':''}${Number(m.amount).toLocaleString('es-MX')}</td><td>${Number(m.balance_after).toLocaleString('es-MX')}</td></tr>)}</tbody></table></div>:<p className="muted">Aún no hay movimientos registrados.</p>}{plus&&<><h2>Cliente Plus · Coleccionables</h2><div className="notice">Antes de enviar cualquier artículo se requiere una llamada con tu agente de La Comarca.</div><div className="actions" style={{marginTop:12}}><button className="btn" disabled={requesting} onClick={()=>request('venta')}>💰 Quiero vender</button><button className="btn2" disabled={requesting} onClick={()=>request('cambio')}>🔄 Quiero cambiar</button></div>{requests.length>0&&<div style={{marginTop:14}}><h3>Mis solicitudes</h3>{requests.map(r=><div className="panel" key={r.id}><b>{r.request_type==='venta'?'Venta':'Cambio'}</b> · {r.status.replaceAll('_',' ')}<br/><span className="muted">{r.notes}</span></div>)}</div>}</>}{msg&&<p>{msg}</p>}<h2>Información de servicio</h2><pre style={{whiteSpace:'pre-wrap',fontFamily:'inherit',lineHeight:1.6}}>{disclaimer}</pre></div></main></>}
