"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {supabaseBrowser} from "../../../lib/supabase";
const labels:any={pending:"Pendiente",contacted:"Contactado",paid:"Pagado",preparing:"Preparando",shipped:"Enviado",completed:"Completado",cancelled:"Cancelado"};
const dateFmt=(v:any)=>new Date(v).toLocaleString("es-MX",{dateStyle:"medium",timeStyle:"short"});
export default function Operaciones(){const router=useRouter(),sb=supabaseBrowser();const[orders,setOrders]=useState<any[]>([]),[alerts,setAlerts]=useState<any[]>([]),[low,setLow]=useState<any[]>([]),[imports,setImports]=useState<any[]>([]),[checking,setChecking]=useState(true),[error,setError]=useState("");
 async function load(){setChecking(true);setError("");try{const[o,a,c,i]=await Promise.all([sb.from('orders').select('id,customer_name,status,total,created_at,notes').order('created_at',{ascending:false}).limit(100),sb.from('order_alerts').select('*').eq('status','open').order('created_at',{ascending:false}),sb.from('cards').select('id,name,stock,price,categories(name)').lte('stock',2).order('stock'),sb.from('inventory_import_audit').select('*').eq('status','pending').order('created_at',{ascending:false})]);if(o.error)throw o.error;if(a.error&&a.error.code!=="42P01")throw a.error;setOrders(o.data||[]);setAlerts(a.data||[]);setLow(c.data||[]);setImports(i.data||[])}catch(e:any){setError(e.message||'No fue posible cargar el centro de operaciones.')}setChecking(false)}
 useEffect(()=>{(async()=>{const{data:u}=await sb.auth.getUser();if(!u.user){router.replace('/login');return}const{data:p}=await sb.from('profiles').select('role').eq('id',u.user.id).maybeSingle();if(p?.role!=='admin'){router.replace('/login');return}load()})()},[]);
 const count=(s:string)=>orders.filter(o=>o.status===s).length;
 const derivedAlerts=orders.filter(o=>['pending','contacted','paid'].includes(o.status)).map(o=>({id:`order-${o.id}`,order_id:o.id,body:o.status==='pending'?'Pedido pendiente de atención.':o.status==='contacted'?'Pedido contactado: requiere seguimiento.':'Pago confirmado: requiere preparación.',created_at:o.created_at,derived:true,status:o.status}));
 const allAlerts=[...alerts.map(a=>({...a,derived:false})),...derivedAlerts.filter(d=>!alerts.some(a=>a.order_id===d.order_id))].sort((a:any,b:any)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime());
 return checking?<main className="wrap"><div className="empty">Cargando operaciones...</div></main>:<><header className="top"><a href="/admin">← Administración</a><b>Centro de Operaciones</b><div className="actions"><button className="btn2" onClick={load}>↻ Actualizar</button><a href="/admin/orders">📦 Pedidos</a><a href="/operativo">📝 Panel Operativo</a></div></header><main className="wrap">{error&&<div className="notice">⚠️ {error}</div>}<div className="panel"><h1>Centro de Operaciones</h1><div className="row">{['pending','paid','preparing','shipped'].map(s=><div className="panel" key={s}><b>{labels[s]}</b><div style={{fontSize:28}}>{count(s)}</div></div>)}</div></div><div className="panel" style={{border:'2px solid #d97706'}}><h2 style={{fontSize:24}}>🚨 ALERTAS QUE REQUIEREN ATENCIÓN ({allAlerts.length})</h2>{allAlerts.length?allAlerts.map((a:any)=><div className="notice" key={a.id} style={{marginTop:10,padding:16,fontSize:16,border:'1px solid #dc2626'}}><b>🔴 {a.derived?'ATENCIÓN OPERATIVA':'ALERTA'}</b><br/>Pedido <b>{a.order_id.slice(0,8).toUpperCase()}</b> · {a.body}<br/><span className="muted">{dateFmt(a.created_at)}</span>{a.derived&&<div style={{marginTop:8}}><button className="btn2" onClick={()=>router.push('/admin/orders')}>Abrir pedidos</button></div>}</div>):<p className="muted">Sin alertas pendientes.</p>}</div><div className="panel"><h2>📥 Importaciones pendientes ({imports.length})</h2>{imports.length?imports.map(i=><div className="notice" key={i.id}>{i.file_name} · {i.created_rows} productos · {i.details?.actor_email||i.actor_id}</div>):<p className="muted">No hay cargas pendientes.</p>}</div><div className="panel"><h2>⚠️ Stock bajo ({low.length})</h2>{low.length?low.slice(0,30).map(c=><div key={c.id} className="row"><b>{c.name}</b><span>Stock: {c.stock} · ${Number(c.price).toLocaleString('es-MX')}</span></div>):<p className="muted">Sin productos con stock bajo.</p>}</div><div className="panel"><h2>📦 Últimos pedidos</h2>{orders.slice(0,20).map(o=><div key={o.id} className="row" style={{padding:'10px 0',borderBottom:'1px solid rgba(127,127,127,.15)'}}><span><b>#{o.id.slice(0,8).toUpperCase()}</b> · {o.customer_name||'Cliente'}<br/><span className="muted">📅 {dateFmt(o.created_at)}</span></span><span>{labels[o.status]||o.status} · ${Number(o.total).toLocaleString('es-MX')}</span></div>)}</div></main></>}
