"use client";
import {useMemo,useState} from 'react';
type Node={id:string;name:string;city:string;balance:number};
type Move={id:string;date:string;from:string;to:string;amount:number;note:string};
const initial:Node[]=[{id:'armando',name:'Armando',city:'CDMX',balance:18500},{id:'pepe',name:'Pepe',city:'Puebla',balance:12300},{id:'erick',name:'Erick',city:'Mérida',balance:9700},{id:'rodrigo',name:'Rodrigo',city:'Mérida',balance:6400},{id:'daniel',name:'Daniel',city:'CDMX',balance:5100}];
const seed:Move[]=[{id:'M-0048',date:'13/08/2026 10:42',from:'Armando',to:'Pepe',amount:5000,note:'Compra de producto'},{id:'M-0047',date:'12/08/2026 18:10',from:'Erick',to:'Armando',amount:3200,note:'Reposición'},{id:'M-0046',date:'12/08/2026 13:25',from:'Daniel',to:'Rodrigo',amount:1800,note:'Producto'}];
const money=(n:number)=>'$'+n.toLocaleString('es-MX',{minimumFractionDigits:2});
export default function Home(){const[nodes,setNodes]=useState(initial),[moves,setMoves]=useState(seed),[from,setFrom]=useState('armando'),[to,setTo]=useState('pepe'),[amount,setAmount]=useState(''),[note,setNote]=useState(''),[msg,setMsg]=useState('');const total=useMemo(()=>nodes.reduce((a,n)=>a+n.balance,0),[nodes]);function transfer(e:React.FormEvent){e.preventDefault();const v=Number(amount);const src=nodes.find(n=>n.id===from),dst=nodes.find(n=>n.id===to);if(!v||v<=0)return setMsg('Indica un importe válido.');if(!src||!dst||src.id===dst.id)return setMsg('Selecciona origen y destino diferentes.');if(src.balance<v)return setMsg('Saldo insuficiente.');setNodes(ns=>ns.map(n=>n.id===src.id?{...n,balance:n.balance-v}:n.id===dst.id?{...n,balance:n.balance+v}:n));setMoves(ms=>[{id:'M-'+String(49+ms.length).padStart(4,'0'),date:new Date().toLocaleString('es-MX'),from:src.name,to:dst.name,amount:v,note:note||'Movimiento interno'},...ms]);setAmount('');setNote('');setMsg('Transferencia registrada correctamente.');}
return <main className="shell"><header className="top"><div className="brand"><div className="eyebrow">SISTEMA INTERNO · NODOS</div><h1>TORRE DE LOS MAGOS</h1><p>Wallet de movimientos entre nodos</p></div><div className="status">● OPERANDO</div></header><div className="wrap"><section className="hero"><div><div className="label">BALANCE CONSOLIDADO</div><div className="total">{money(total)}</div><div className="muted">Fondos registrados entre todos los nodos</div></div></section><section className="nodes">{nodes.map(n=><article className="node" key={n.id}><small>{n.city}</small><strong>{n.name}</strong><div className="balance">{money(n.balance)}</div><small>Saldo disponible</small></article>)}</section><section className="grid"><div className="panel"><div className="label">OPERACIÓN</div><h2>Nueva transferencia</h2><form onSubmit={transfer}><label>ORIGEN</label><select value={from} onChange={e=>setFrom(e.target.value)}>{nodes.map(n=><option value={n.id} key={n.id}>{n.name} · {money(n.balance)}</option>)}</select><label>DESTINO</label><select value={to} onChange={e=>setTo(e.target.value)}>{nodes.map(n=><option value={n.id} key={n.id}>{n.name} · {n.city}</option>)}</select><label>IMPORTE MXN</label><input type="number" min="1" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0.00"/><label>CONCEPTO</label><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Motivo del movimiento"/><button className="btn">Transferir fondos →</button>{msg&&<p className="muted">{msg}</p>}</form></div><div className="panel"><div className="label">TRAZABILIDAD</div><h2>Movimientos recientes</h2>{moves.map(m=><div className="movement" key={m.id}><div className="icon">↗</div><div><strong>{m.from} → {m.to}</strong><span>{m.note}</span><small>{m.date} · {m.id}</small></div><b>{money(m.amount)}</b></div>)}</div></section></div></main>}
